FROM node:latest as build
WORKDIR /usr/local/app
COPY . .
RUN npm install
CMD ["npm", "run" , "build", "--prod"]
FROM nginx:latest
COPY /usr/local/app/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/local/app/dist/frontend /usr/share/nginx/html
EXPOSE 80